### ISSUE TITLE
SPIFSS "available" message

### ISSUE THREAD

**Issue by venice1200** [jp112sdl/AskSinAnalyzer#11]
Hi,
in line 159 of "AskSinAnalyzerESP32.ino" **sdAvailable** must be replaced with **spiffsAvailable** to get the correct information shown.

`DPRINT(F("- INIT SPIFFS  DONE. SPIFFS  IS ")); DPRINTLN(sdAvailable ? "AVAILABLE" : "NOT AVAILABLE");`

Cheers
Lars

**Comment by jp112sdl** [comment]
Thx! 👍
