### ISSUE TITLE
OTA from WebUI

### ISSUE THREAD

**Issue by gulalo** [jp112sdl/AskSinAnalyzer#12]
Hi Jérôme,
vielen Dank für das super Tool!
Habe OTA versucht über WebUI,scheint aber nicht zu laufen.
von Version 1.3-->1.4
es erscheint: https://raw.githubusercontent.com/jp112sdl/AskSinAnalyzer/master/ota/AskSinAnalyzerESP32.bin
weiter passiert aber nichts, bzw. wie lange kanns dauern?
Habe ich etwas übersehen??

**Comment by jp112sdl** [comment]
Hi!
Ich sage mal so ca. 30 Sekunden.

Im seriellen Monitor müsste was mit "Check for Update..." kommen - dann eine ganze Weile nix und dann der Reboot

**Comment by chkbln** [comment]
Hi,
bei mir funktioniert das Update auch nicht.
Nach dem Klick auf den den Update Button kommt
https://raw.githubusercontent.com/jp112sdl/AskSinAnalyzer/master/ota/AskSinAnalyzerESP32-ND.bin

![grafik](https://user-images.githubusercontent.com/11814828/60464415-d23b6200-9c4e-11e9-98e7-7e82a10439db.png)

Der ESP ist dann auch nicht mehr über die IP erreichbar.
Nach dem Neustart funktioniert er wieder, aber mit der alter Version 1.3.
Im seriellen Monitor wird "Check for Update..." nicht angezeigt
Gruß

**Comment by jp112sdl** [comment]
Es gibt nun noch zahlreiche Möglichkeiten, weshalb es nicht klappt..., zB. wenn du die 1.3 mit der neuesten Version von AsyncTCP und ESP32 Board 1.0.2 kompiliert hattest, was nun zu einem WDT Reset führt (ist mit 1.4 behoben).

Am besten du kompilierst die 1.4 noch mal selbst und lädst sie auf den ESP32

**Comment by psi-4ward** [comment]
Was genau heißt: 
> Nach dem Klick auf den den Update Button kommt
https://raw.githubusercontent.com/jp112sdl/AskSinAnalyzer/master/ota/AskSinAnalyzerESP32-ND.bin

Im Browser sollte dann etwas stehen wie 

`http://<espip>/httpupdate?url=https://raw.githubusercontent.com/jp112sdl/AskSinAnalyzer/master/ota/AskSinAnalyzerESP32-ND.bin`

**Comment by chkbln** [comment]
@psi-4ward 
ich habe jetzt, wie Jérôme empfohlen hat, die Version 1.4 neu kompiliert und auf den ESP32 geladen.
Kann das Fehlerbild also nicht mehr reproduzieren.

**Comment by psi-4ward** [comment]
Na dann machen wir issue mal zu. Sofern wieder Probleme auftauchen gehen wir es noch einmal an. Ich hab heute auch noch mal von 1.3 auf 1.4 das Update gemacht
