### ISSUE TITLE
anderes Display - Anschlusspins

### ISSUE THREAD

**Issue by vr6syncro** [jp112sdl/AskSinAnalyzer#21]
Moin, habe leider nicht das exakt gleiche Display sonder folgendes:(https://www.aliexpress.com/item/32859737322.html?spm=a2g0s.9042311.0.0.27424c4dNK3oXj)
Nun habe ich aber leider keinerlei Infos zum Anschluss gefunden. Die Pins am ESP32 sehe ich ja und kann die zuordnen nur leider fehlen mir die Pins am Display. Beispiel: ESP D6 -> Display IRQ.
Hoffe ist verständlich was mir fehlt.

Danke für das tolle Projekt, Gruß Alex

**Comment by jp112sdl** [comment]
Hi, das Display ist leider nicht geeignet, da es keinen SPI Anschluss besitzt.
