### ISSUE TITLE
Web: neue Funktion "Geräteliste von CCU neu laden"

### ISSUE THREAD

**Issue by jp112sdl** [jp112sdl/AskSinAnalyzer#26]
Hi,
bitte in der Weboberfläche einen weiteren Button (rechts in der Box über Reboot?) hinzufügen, mit dem man die Geräteliste neu von der CCU laden kann.

:warning: Achtung:
:x: Die Funktion `/getAskSinAnalyzerDevList` ist ab sofort veraltet.
:heavy_check_mark: Bitte jetzt  `/getAskSinAnalyzerDevListJSON` nutzen. 
Es wird jetzt nur noch das JSON Array ausgegeben, ohne den XML Overhead.
Und beim Aufruf wird auch gleichzeitig die interne Device-Liste (fürs TFT Display) erneuert, so spare ich einen GET.

**Comment by psi-4ward** [comment]
Implemented in a356b94a3664d2e5dda492bff14d90fd8233bccb
