### ISSUE TITLE
WebUI: Load CSV

### ISSUE THREAD

**Issue by psi-4ward** [jp112sdl/AskSinAnalyzer#29]
Ability to load and display the telegrams from the CSV.

@jp112sdl Can you send me an example file? My Analyzer doesn't have an sd-slot.

**Comment by jp112sdl** [comment]
Die CSV wird dann im SPIFFS geschrieben. Du kannst sie dir trotzdem von deinem ESP herunterladen.
Sollte keine CSV existieren, wäre das ein Bug. Dann neues Ticket
