### ISSUE TITLE
CR: show every single flag in 'Flags' as colored rounded rectangle

### ISSUE THREAD

**Issue by jp112sdl** [jp112sdl/AskSinAnalyzer#3]
each flag has its own color.
i.e.:
- BCAST: LIGHTGREY
- INFO: BLUE
- ...

**Comment by psi-4ward** [comment]
Do we have a list of all possible flags?
Do you prefer specific colors like blue for info?

**Comment by jp112sdl** [comment]
_Sorry - INFO was wrong!_

The flags can be
- "WKUP "
- "WKMEUP "
- "BCAST "
- "BURST "
- "BIDI "
- "RPTED "
- "RPTEN "

The flags `RPTED` and `RPTEN` are imho unimportant.
They can be shown in a lightweight color

`BURST` can be red - causes high DC.
`BIDI` maybe orange

`BCAST` is a non-acknowledged message so it can be in a light grey

`WKUP` and `WKMEUP` have informational character. The should not be an eye catcher...

**Comment by jp112sdl** [comment]
Only show a small colored rounded rectangle without text, but always on its fixed position.
Show a legend on the top of the page

**Comment by psi-4ward** [comment]
Tried it, looks not very good and in my op bad user experience. I'll dense the flags a bit more.
