### ISSUE TITLE
WebUI: Device Detail-View

### ISSUE THREAD

**Issue by psi-4ward** [jp112sdl/AskSinAnalyzer#30]
Does it make sense to have an detailed view for a specific device? Ie to chart it's RSSI over time? 
This issue is somewhat a brainstorming so pls tell me your ideas :)

**Comment by jp112sdl** [comment]
Geräte sind üblicherweise fest an einem Standort platziert. Da ändert sich nicht viel.
Aber bau ins Web ein was du magst. Mehr Funktionen sind immer gut. Ob sie genutzt werden und sich der Aufwand lohnt, kann man nicht sagen
