### ISSUE TITLE
Web: Lauffähigkeit nur mit aktuellster ESP-Version

### ISSUE THREAD

**Issue by jp112sdl** [jp112sdl/AskSinAnalyzer#31]
Die Webansicht sollte nur arbeiten, wenn die ESP32 Version der aktuellsten entspricht.
Bei Abweichung erscheint ein Popup mit dem Hinweis, dass ein Update durchgeführt werden muss. Darin enthalten dann bestenfalls gleich der Update-Button.

**Comment by psi-4ward** [comment]
Hab mich dazu entschieden nur einen Banner einzuführen, ggf. ist die Lauffähigkeit ja dennoch gegeben.

**Comment by jp112sdl** [comment]
Ok. Zumindest hat der Nutzer dann einen Hinweis, falls irgendwas nicht läuft wie es soll. 👍
