### ISSUE TITLE
Anzeige des Namens von Serial "HmIP-RF" leider immer noch schwarz

### ISSUE THREAD

**Issue by venice1200** [jp112sdl/AskSinAnalyzer#32]
Hallo,
habe gerade (2019-08-16/9:00) die aktuellste Version gezogen und installiert.
Leider wird im Web der Name von "HmIP-RF" noch immer schwarz dagestellt.

Auszug aus der Device List:
{"address":12470xxx,"serial":"HmIP-RF","name":"HmIP-CCU"}

![2019-08-16 08_53_19-Window](https://user-images.githubusercontent.com/43762187/63149730-3c447680-c005-11e9-8f24-e5f37a7ea0dd.png)

Reference: #28 

Danke :-)

//Edit
...hat ja erst einmal nix mit dem ESP Sketch zu tun.

**Comment by venice1200** [comment]
Sowohl in der "Von" als auch im "An" Spalte.

![2019-08-16 09_18_31-Window](https://user-images.githubusercontent.com/43762187/63150381-eec90900-c006-11e9-9429-1de438e73a6e.png)

**Comment by venice1200** [comment]
Hab mir jetzt erst einmal so geholfen indem ich im HM Programm 7 Freizeichen an den String "HmIP-RF" angehängt habe damit der String (die Serial) 14 Zeichen lang ist Somit ist "isIP" erfüllt.

if ((HmIPCentral > 0) && (data == HmIPCentral)) { ser = "HmIP-RF       "; }

VG
Lars

**Comment by psi-4ward** [comment]
Lass mich wissen wenns noch Probleme gibt ;)
