### ISSUE TITLE
Telegram counter is off center

### ISSUE THREAD

**Issue by stan23** [jp112sdl/AskSinAnalyzer#34]
especially for large numbers:

![counter](https://user-images.githubusercontent.com/4477518/63286815-2f4fad80-c2b9-11e9-94aa-dafb1f2b5cb8.jpg)

**Comment by jp112sdl** [comment]
Oh ha... wie lange läuft die Kiste bei dir für diese Anzahl an Messages?

**Comment by stan23** [comment]
> 
> Oh ha... wie lange läuft die Kiste bei dir für diese Anzahl an Messages?

Nicht ganz eine Woche. Die Wandthermostate sind sehr mitteilungsbedüftig.

**Comment by jp112sdl** [comment]
Dann muss ich mein Session-Logging Konzept noch mal überdenken. 
Hab nicht damit gerechnet, dass jemand das Gerät so lange laufen lässt 😄
