### ISSUE TITLE
AskSinAnalyzerESP32.ino

### ISSUE THREAD

**Issue by audi2010** [jp112sdl/AskSinAnalyzer#37]
Hallo Jerome,
wo kommt den die Datei Zeile 15 "<Preferences.h>" her.
Die fehlt mir.

**Comment by jp112sdl** [comment]
Hi!

Was meinst du mit "wo kommt die her?"

Sie ist Teil des ESP32-Boards und wird automatisch mit ausgeliefert.
https://github.com/espressif/arduino-esp32/tree/master/libraries/Preferences/src

**Comment by psi-4ward** [comment]
Du hast wahrscheinlich einfach die falsche Lib erwischt.
Ist mir auch passiert. Kannst du nicht einfach das Hex flashen oder hast du Anpassungen vorgenommen?

Alternativ zur Arduino IDE könntest du PlatformIO verwenden, dem Ordner liegt eine `platformio.ini` bei welche alle nötigen Libs referenziert. Es reicht in dem Fall ein `platformio run -t upload` und es wird alle nötige heruntergeladen, compiliert und geflasht.

**Comment by jp112sdl** [comment]
> Du hast wahrscheinlich einfach die falsche Lib erwischt.

Wie schafft man das?

**Comment by audi2010** [comment]
Ich schaff alles :)
Auf einem anderen Rechner läufts problemlos.
Danke für die Tips

**Comment by jp112sdl** [comment]
Hier kann wohl zu
