### ISSUE TITLE
CR: new items in menu

### ISSUE THREAD

**Issue by jp112sdl** [jp112sdl/AskSinAnalyzer#4]
add to the menu (Einstellungen, Info) the following items:

- Reboot (calls `/reboot`)
- Reboot AP-Mode (calls `/rebootconfig`) to start the config mode
- Download CSV (calls `/downloadcsv`)
- Delete CSV (calls `/deletecsv`)

**Comment by psi-4ward** [comment]
54d8dd9

@jp112sdl Teste das Zeug mal, kA ob das auf Anhieb funktioniert :)

**Comment by jp112sdl** [comment]
Geht.
