### ISSUE TITLE
ESP OTA

### ISSUE THREAD

**Issue by gulalo** [jp112sdl/AskSinAnalyzer#40]
Habe OTA  ESP update von 2.3 nach 2.5 gestartet, mehrfach versucht,es tut sich nix.
neu flashen?

**Comment by jp112sdl** [comment]
Ggf. mal schauen, was im seriellen Monitor ausgegeben wird.
Ansonsten -> ja, dann neu flashen.

**Comment by pekae** [comment]
Bei mir hatte der Werbe- und Popup-Blocker des Browser das auch verhindert. Blocker aus, OTA geht


Mit freundlichen Gruß

Peter Kästner

**Comment by psi-4ward** [comment]
Ich kann hier was verbessern

**Comment by jp112sdl** [comment]
@psi-4ward *was* verbessern?

**Comment by psi-4ward** [comment]
Anstatt dem neuen Fenster / pop-up könnte man auch einen xhr request im Hintergrund durchführen.
