### ISSUE TITLE
Alternative DevList-Eingabe im WebUI

### ISSUE THREAD

**Issue by t0mx** [jp112sdl/AskSinAnalyzer#44]
Ich benutze FHEM als Homematic-Zentrale für BidCos-Geräte und eine CCU für HMIP. Im Moment wird nur CCU als Datenlieferant unterstützt und auch nur 1X. Einfacheit halber könnte man direkt in der WebUI eine Liste der Geräte bzw. deren Alias/Namen pflegen.
Vorschlag zur Umsetzung:
- Ein Textfeld, in dem man mit einer definierten Sysntax die HMIDs und deren Aliase eingibt, z.B. zeilenweise:
**FF1234 Bad_Licht
AB1524 Flur_LED**
oder wie von papa im Forum vorgeschlagen:
**{
  "Arg":"TYPE=CUL_HM:FILTER=serialNr!= DEF alias serialNr",
  "Results": [
  {
    "Name":"HM_000067",
    "Internals": {      "DEF": "000067" },
    "Readings": { },
    "Attributes": {
      "alias": "Treppe Unten Dimmer",
      "serialNr": "HMDi000067"
    }
  },
  {
    "Name":"HM_000068",
    "Internals": {      "DEF": "000068" },
    "Readings": { },
    "Attributes": {
      "alias": "Dimmer Regal",
      "serialNr": "HMDi000068"
    }
  },
  {
    "Name":"HM_001A00",
    "Internals": {      "DEF": "001A00" },
    "Readings": { },
    "Attributes": {
      "alias": "Dash Button",
      "serialNr": "HMRC001A00"
    }
  }**

**Comment by jp112sdl** [comment]
AskSinAnalyzer >= 3.1 unterstützt nun auch FHEM / andere Geräteliste-Quellen
