### ISSUE TITLE
ESP32 Belegung

### ISSUE THREAD

**Issue by tis-cs** [jp112sdl/AskSinAnalyzer#47]
Moin,
ich habe hier leider ein ESP32 Board mit jeweils nur 15 Pinnen pro Seite. Wäre es möglich, dass die Anleitung der Verdrahtung diesbezüglich nicht nur ein Bild zeigt sondern auch die Pinbeschreibung enthält?

Danke im Voraus!

![image](https://user-images.githubusercontent.com/24519878/71315050-88407580-2454-11ea-9306-005657f36144.jpg)

**Comment by stan23** [comment]
Servus,
du könntest dich an den Pinnamen hier im PDF orientieren:
https://github.com/stan23/myPCBs/blob/master/AskSinAnalyzer/AskSinAnalyzer_V2.0_Schematic.pdf

Die Pins zum Touch-Controller (T_*) sind optional und nicht von der SW unterstützt.

**Comment by tis-cs** [comment]
@stan23 Vielen Dank für den Hinweis. Allerdings bekomme ich aus dem Dokument keinen Zusammenhang bzw. eine Zuordnung zu meinem ESP32 hin. Verstehe ich etwas grundlegendes nicht oder was mache ich falsch? 

Könntest du mir ein zwei Beispiele anhand meines Bildes machen (z.B. Display zum ESP)

Vielen lieben Dank!

**Comment by jp112sdl** [comment]
Im Sketch findest du die Pins, wie sie auch auf deinem Board stehen:
```
#define TFT_LED                 33
#define TFT_CS                   5
#define TFT_RST                 26
#define TFT_DC                  25
```
MISO ist Pin19 
MOSI ist Pin23

**Comment by stan23** [comment]
Wenn du die wiring.fzz mit Fritzing öffnest, siehst du die Pinnamen.

Ich hoffe ich habe alle richtig übertragen:
![wiring](https://user-images.githubusercontent.com/4477518/71365595-c5fde500-259f-11ea-9cf2-650c90f4e9a1.png)

**Comment by tis-cs** [comment]
Super, danke euch beiden für die Hilfe.
