### ISSUE TITLE
Importieren von LOG in die WEB nicht möglich...

### ISSUE THREAD

**Issue by ThomasLoeffel** [jp112sdl/AskSinAnalyzer#48]
Hallo Zusammen,

danke für Eure "SUPER" Arbeit! Folgendes ist mir aufgefallen.
Im WEBUI beim Start bekomme ich bei mir max 1h angezeigt. Somit dachte ich das ich nach einem CSV download (25.12 bis dato) und Import der gleichen Datei zurück mehr angezeigt bekomme. Der Import startet aber augenscheinlich nicht. Nur Bereich Telegramme pro Device wird "weiss" aber sonst passiert nichts. Mache ich was falsch?

Lieben Gruß Thomas

![grafik](https://user-images.githubusercontent.com/44590735/71534258-d692c000-28fd-11ea-9940-428589fc5eaf.png)

![grafik](https://user-images.githubusercontent.com/44590735/71534299-338e7600-28fe-11ea-96c0-3efc4b37a29d.png)

**Comment by jp112sdl** [comment]
Hallo Thomas, tritt das Problem immer noch auf?

**Comment by ThomasLoeffel** [comment]
Hallo Jerome,

ich verwende die Version 3.2 (gerade heraus gekommen). Ja der Fehler ist immer noch so. Ich habe es selbst mit kleinsten Dateien versucht. 1 min Asksin laufen lassen. CSV Download "Name: log.csv". Dann Asksin neu starten und Import der Datei"log.csv". der blaue Button blinkt einmal, das Kreisdiagramm ist leer. Aber das Importfenster verschwindet nicht. Sonst keine Reaktion bis ich das Browserfenster aktualisiere. Dann alles wie immer, aber ohne log.csv Daten. Ich benutze Firefox.

Danke für Deine super Arbeit und hoffe auf eine Aufklärung :-).
Gruß Thomas

**Comment by jp112sdl** [comment]
Kannst du mal eine CSV hier anhängen, um das Problem evtl. reproduzieren zu können?

**Comment by ThomasLoeffel** [comment]
[log.txt](https://github.com/jp112sdl/AskSinAnalyzer/files/4205948/log.txt)

**Comment by psi-4ward** [comment]
Cool. Ich schau mir das am Sonntag an. Welchen Browser auf welchem OS hast du?

**Comment by ThomasLoeffel** [comment]
System: Win10 pro, Browser: Firefox 73.0 (64-Bit), komischerweise lässt das WebUi mit MS Edge nicht anzeigen.

**Comment by ThomasLoeffel** [comment]
Nur am Rande erwähnt. Mit der Version 3.2 funktioniert ein Reboot bei mit nicht mehr zuverlässig. Das bedeutet das in 6 von 10 Fällen der Asksin nicht mehr hochfährt (kleine grüne Punkt wird nicht voll). Dann hilft nur Strom aus/an.

**Comment by ThomasLoeffel** [comment]
Zusatz: Kann aber auch an dem Problem mit dem Import liegen.... Habe eben ohne Import zu nutzen den Reboot probiert und da ist es "0" mal passiert.

**Comment by ThomasLoeffel** [comment]
Zusatz: Kann aber auch an dem Problem mit dem Import liegen.... Habe eben ohne Import zu nutzen den Reboot probiert und da ist es "0" mal passiert.

**Comment by psi-4ward** [comment]
Sooo teste mal bitte ;)
CSV + (dummer blöder) Edge sollte nun gehen

**Comment by ThomasLoeffel** [comment]
Mal eine dumme abschließende Frage:
Da Du keine neue Version vergeben hast, muss ich dann selbst compilieren und mit Arduino IDE drauf spielen? Oder gibt es einen einfacheren Weg?

Gruß und Danke !!
Thomas

**Comment by psi-4ward** [comment]
Nein, die Version bezieht sich auf die Software auf dem ESP. Die WebUI wird aus der _Cloud_ (von Github) gezogen und sollte demnach aktuell sein. Ggf. musst du den Browser-Cache löschen.

**Comment by ThomasLoeffel** [comment]
Hat super geklappt :-). Geht alles wie von Dir erwartet. 
Idee: Kann man ggf die ESP-Version und die UI-Version auf dem Display (auf dem ESP) auf der Seite mit den Netzwerkdaten hinterlegen? 

Lieben Gruß und vielen Dank Thomas !!!
