### ISSUE TITLE
Idee: Anbinden mySQL z.B. Synology Maria10 DB

### ISSUE THREAD

**Issue by ThomasLoeffel** [jp112sdl/AskSinAnalyzer#49]
Hallo Zusammen,

da ich IOBROKER zur Auswertung benutze habe ich mir gedacht dass der AskSinAnalyser auch eine Anbindung zu meinem mySQL Server auf meiner Synology (Maria 10 DB) aufbauen kann um da die LOG Einträge zu speichern.

Lieben Gruß Thomas

**Comment by jp112sdl** [comment]
Hmm... ich persönlich hab da eher weniger Interesse dran.
Der Wildwuchs an Dritt-Systemen ist zu groß. ioBroker/MySQL ist nur eine Kombination von vielen.
Wo fängt man an, wo hört man auf?

Der Analyzer ist auch eher als Erste-Hilfe-Maßnahme gedacht. 

Für erweiterte Funktionen, am besten das Projekt hier forken und die Funktionen selbst implementieren.
