### ISSUE TITLE
Datenspeicherung

### ISSUE THREAD

**Issue by howy075** [jp112sdl/AskSinAnalyzer#57]
Wäre es möglich, dass der Analyzer täglich eine neue .csv erstellt statt alles in eine Datei zu schreiben?

**Comment by jp112sdl** [comment]
An sich ne gute Idee. 
Jedoch würde man dann beim Klick auf "CSV Download" nur die Tages-CSV bekommen...

Aber ich glaub, das ist vertretbar. 
Wenn man mehr braucht, muss man entweder die SD Karte entnehmen bzw ich bau noch eine Download-URL mit ein, der man das Tagesdatum übergibt

**Comment by jp112sdl** [comment]
Bitte testen. Änderung ist im [dev](https://github.com/jp112sdl/AskSinAnalyzer/tree/dev)-Branch.

"CSV Download" im Web lädt die CSV des aktuellen Tages herunter.
Möchte man einen anderen Tag, so kann man folgende URL aufrufen:
`http://asksinanalyzer.local/download?filename=/yyyymmdd.csv`
- yyyy = Jahr
- mm = Monat
- dd = Tag

**Comment by psi-4ward** [comment]
An dieser Stelle wäre noch ein api endpoint sinnvoll welcher eine Liste an Dateien zurück gibt (json array).

Aber ist Tag nicht etwas fein aufgelöst?

**Comment by jp112sdl** [comment]
> An dieser Stelle wäre noch ein api endpoint sinnvoll welcher eine Liste an Dateien zurück gibt (json array).

An sich ne schicke Idee, dann könnte man die vorhanden Files als Dropdown auflisten und das gewünschte runterladen.
Ich wollt da jetzt aber nicht noch viel Energie reinstecken, vor allem was die WebUI betrifft.

> Aber ist Tag nicht etwas fein aufgelöst?

Kommt sich drauf an, wie viel anfällt.
Bei mir ca. 15k Zeilen pro Tag. Täglich ist schon schick. Monatlich wäre zu lange und wöchentlich ist ein blöder Rhythmus. :)

**Comment by jp112sdl** [comment]
Hab das Directory Listing mal fix mit eingebaut.
Hängt im `/getConfig` mit an, kann auch manuell mit `/listSD` abgefragt werden.

<img width="330" alt="Bildschirmfoto 2020-02-18 um 10 30 16" src="https://user-images.githubusercontent.com/18190139/74722694-a995c600-5239-11ea-9dfa-fddfd3310811.png">

Was damit nun passiert, kannst du (@psi-4ward) dir überlegen 🤓

**Comment by howy075** [comment]
Gefällt mir sehr gut so!
Vielen Dank!

**Comment by howy075** [comment]
Jetzt könnte man evtl darüber nachdenken, ob die webui automatisch die Daten des aktuellen Tages ladet.
Aber das ist wirklich ein Wunsch der gerne unerfüllt bleibt! sind ja eh nur 2-3 klicks.
Grüße
Howy

**Comment by jp112sdl** [comment]
Das wird zu viel... aber wenn man den ganzen Tag haben will, kann man ja auch die CSV uploaden
