### ISSUE TITLE
RSSI Alarm Threshold

### ISSUE THREAD

**Issue by friedpa** [jp112sdl/AskSinAnalyzer#59]
Wenn man den RSSI Alarm Threshold aktiviert und den ASA mit einer (RasberryMatic) RM verbunden hat, kommt nach einem Reset vom ASA immer einmal ein Alarm an der RM an, egal welchen Pegel man eingestellt hat und auch der RSSI Alarm Count hat keinen Einfluss darauf. Ein durchforsten aller Telegramme in der Liste zeigt auch keinen Wert der über dem Threshold liegt an.

**Comment by jp112sdl** [comment]
Hmm, kann ich leider nicht reproduzieren.

Kannst du mal schauen, was der ESP32 an seriellen Ausgaben beim Booten schreibt?

**Comment by friedpa** [comment]
Guten Morgen, bin leider kein Profi so wie Ihr, was genau soll ich machen?

**Comment by jp112sdl** [comment]
Den seriellen Monitor in der Arduino IDE öffnen, 57600 Baud einstellen, dann Reset-Taster am ESP32 drücken

**Comment by friedpa** [comment]
Muss ich sonst noch was umstellen? Wenn ich den ASA an den PC über das USB Kabel anschliesse sehe ich den ASA nicht.

**Comment by friedpa** [comment]
Screenshots:

![grafik](https://user-images.githubusercontent.com/42890695/77637200-94593900-6f55-11ea-9812-dd12e583af18.png)
![grafik](https://user-images.githubusercontent.com/42890695/77637282-b652bb80-6f55-11ea-8be3-50771de63ccc.png)
![grafik](https://user-images.githubusercontent.com/42890695/77637348-cf5b6c80-6f55-11ea-896b-efcdaa8c5f24.png)

**Comment by jp112sdl** [comment]
> Wenn ich den ASA an den PC über das USB Kabel anschliesse sehe ich den ASA nicht.

Wie hast du ursprünglich mal den Sketch geflasht?

**Comment by jp112sdl** [comment]
Der Alarmthreshold mit -120 ist verdammt gering... Mach mal bitte -100 und Alarmcount auf 60

**Comment by friedpa** [comment]
Ich habe das Gerät fertig bekommen :o)
Probiere -100 und 60 melde mich

**Comment by friedpa** [comment]
Nunn mit -100dB und 60

![grafik](https://user-images.githubusercontent.com/42890695/77641239-046abd80-6f5c-11ea-8014-e6c59b0cc26b.png)

**Comment by friedpa** [comment]
Mit -100dB und 60 das selbe Problem

**Comment by jp112sdl** [comment]
Ich seh da in dem Screenshot vorhin gar keine rote RSSI-Linie... ich vermute mal, die ganze Problematik kommt, weil auf dem AskSinSniffer328P noch die alte Firmware läuft.

**Comment by friedpa** [comment]
Ok, das heißt ich muss diese FW updaten .... muss also irgendwie nun den ASA an den PC bekommen .... danke für Deinen Support

**Comment by stan23** [comment]
Du brauchst einen FTDI-Adapter...

**Comment by friedpa** [comment]
OK, danke habe ich... gibt es irgendwo eine Anleitung? Sorry, wenn ich Fragen stelle die für Euch eh klar sind ....

**Comment by jp112sdl** [comment]
Oder dort nachfragen, wo du den AskSinAnalyzer "bezogen" hast... 
Gerät noch mal hinschicken, updaten lassen

**Comment by friedpa** [comment]
Gents, noch eine Frage: ist das Ding überhaupt zum Upgraden?

![grafik](https://user-images.githubusercontent.com/42890695/77657926-40ab1780-6f76-11ea-915d-abcf22899a85.png)

**Comment by stan23** [comment]
Ja ist es, das Platinendesign stammt von mir, Idee und Schaltplan von Jérôme.
Der FTDI muss am J21 um den ATmega zu aktualisieren.

**Comment by friedpa** [comment]
Dann habe ich das Ding eh von Dir :o) Du hast damals mehrere Platinen in China bestellt und da durfte ich mitbestellen :o) D.h. ich löte um J21 eine Stiftreihe an und mit einem FTDI Adapter dann das Upgrade.... Gibt es dazu vielleicht eine Anleitung :o)

**Comment by psi-4ward** [comment]
Nichts einlöten, steck den FTDI einfach so rein, das sollte ausreichen.
Anleitung gemäß https://github.com/jp112sdl/AskSinAnalyzer/tree/master/AskSinSniffer328P

Siehe auch https://asksinpp.de

**Comment by friedpa** [comment]
Super! Danke! Erst jetzt sehe ich, dass da ja stan23 auf der Platine steht, also chatte ich mit den Chefs persönlich :o) Nochmals vielen Dank für das Super Projekt!!!

**Comment by friedpa** [comment]
Habe jetzt die FW upgedatet und der Alarm kommt jetzt nicht mehr. Vielen Dank für den Hint und die guidance durch die Problemstellung.
