### ISSUE TITLE
CR: Anzeige des Speicherplatzes SD / SPIFFS in Titelleiste

### ISSUE THREAD

**Issue by jp112sdl** [jp112sdl/AskSinAnalyzer#6]
`/getConfig` gibt nun auch Informationen zum Speicherplatz aus.
```
{"staticip":"0.0.0.0","staticnetmask":"0.0.0.0","staticgateway":"0.0.0.0","ccuip":"192.168.1.252","svanalyzeinput":"Analyzer_Input","svanalyzeoutput":"Analyzer_Output","resolve":1,"sdcardavailable":1,"sdcardsizemb":3780,"sdcardtotalspacemb":"2047","sdcardusedspacemb":"3","spiffssizekb":1342,"spiffsusedkb":79}
```

|Parameter|Bezeichnung|
|-----|-----|
| sdcardavailable|SD Karte verfügbar? 1=ja, 0=nein|
| sdcardsizemb|Gesamtgröße der SD Karte in **MB**|
| sdcardtotalspacemb |Gesamtgröße der Partition in **MB**|
| sdcardusedspacemb |belegter Speicherplatz in **MB**|
| spiffssizekb |Größe des SPIFFS in **kB**|
| spiffsusedkb |belegter Speicherplatz des SPIFFS in **kB**|

Die Speicherplatzverwendung könnte auch in % ausgegeben werden o.ä.

**Comment by psi-4ward** [comment]
see dfea90294e62ef7bd06e6c7fe60580c90668d374
