### ISSUE TITLE
DevList fetch from httpS

### ISSUE THREAD

**Issue by psi-4ward** [jp112sdl/AskSinAnalyzer#61]
In der [FHEM Community](https://forum.fhem.de/index.php/topic,102701.msg1041899.html#msg1041899) kam die Frage auf die DevList von httpS zu holen.

Ggf wäre die Implementierung gar nicht so komplex:

https://github.com/jp112sdl/AskSinAnalyzer/blob/master/AskSinAnalyzerESP32/Helper.h#L87

Nach etwas google _könnte_ es reichen aus `HTTPClient` einen `WiFiClientSecure` zu machen.

**Comment by jp112sdl** [comment]
Ja, reicht aus.
