### ISSUE TITLE
Empfänger in Webfrontend / Display stimmt nicht überein

### ISSUE THREAD

**Issue by mdk2412** [jp112sdl/AskSinAnalyzer#64]
Hallo,

seit kurzem fällt mir auf, dass laut Webfrontend einige meiner Sensoren angeblich an eine Verknüpfung senden (die jedoch nur mehrere Jalousien/Rollläden verknüpft, die Sensoren sind da nicht drin). Im Display steht bei dem gleichen Telegramm allerdings richtigerweise als Empfänger "Zentrale". Ist das ein Fehler auf meiner Seite oder im Code?

**Comment by jp112sdl** [comment]
Mir fällt da pauschal nix zu ein

**Comment by mdk2412** [comment]
Ich hab jetzt mal den Namen der Verknüpfung geändert und die Device List neu geladen. Statt Zentrale kommt dann der geänderte Name der Verknüpfung. Mit anderem Browser/auf anderem Gerät sieht das genauso aus. Wo wird denn aufgelöst, welches Gerät die Zentrale ist? An der Stelle scheint es im Webfrontend schief zu gehen. Auf dem Display ist ja alles korrekt.

**Comment by psi-4ward** [comment]
Das passiert in dieser Gegend: https://github.com/jp112sdl/AskSinAnalyzer/blob/master/ui/src/EspService.js#L194

Also versteh ich dich richtig, deine Sensoren schicken laut WebUI Telegramme an die Zentrale aber das ist nicht richtig?

**Comment by mdk2412** [comment]
Nein, es ist so: im Webfrontend wird bei jedem Telegramm sowohl bei "AN" als auch "VON" der Name einer Verknüpfung XY angezeigt anstelle des zu erwartenden "ZENTRALE". Im Analyzer-Display wird bei dem identischen Telegramm korrekt "ZENTRALE" angezeigt. Wenn man sich statt der Namen nur die IDs anzeigen lässt, steht da, wo der Name der Verknüpfung angezeigt wird, die richtige ID der CCU. Es wird also der Name der CCU falsch aufgelöst, aber das nur im Webfrontend, nicht im Display.

**Comment by psi-4ward** [comment]
Lass da mal bei Gelegenheit noch mal drüber reden

**Comment by jp112sdl** [comment]
> Lass da mal bei Gelegenheit noch mal drüber reden

Ich glaub nicht, dass sich diese Gelegenheit noch ergeben wird ;)
