### ISSUE TITLE
[regression] ccu_create_devlist.txt: HmIPCentral system.Exec broken after commit b325ebbe1c17766bb87b4b31e1f8c595fcc4af83

### ISSUE THREAD

**Issue by Yannik** [jp112sdl/AskSinAnalyzer#69]
Hi,

your commit https://github.com/jp112sdl/AskSinAnalyzer/commit/b325ebbe1c17766bb87b4b31e1f8c595fcc4af83 unfortunately breaks correctly setting `HmIPCentral` in the `ccu_create_devlist.txt` script for me. 

After the [system.exec](https://github.com/jp112sdl/AskSinAnalyzer/blob/b325ebbe1c17766bb87b4b31e1f8c595fcc4af83/additional/ccu_create_devlist.txt#L62), `stdout` is empty for me.

Reverting the commit fixes this.

**Comment by jp112sdl** [comment]
Hi, which firmware version is your ccu (ccu2 / 3 / raspberrymatic) running at?

**Comment by Yannik** [comment]
3.51.6

**Comment by jp112sdl** [comment]
Hmm...
Does `WriteLine(stderr);` show anything?

**Comment by Yannik** [comment]
It does:

`/bin/sh: 1: arithmetic expression: expecting EOF: "16#B2531A"`

**Comment by jp112sdl** [comment]
Please try
```
system.Exec("echo $((0x`grep Adapter.1.Address /etc/config/hmip_address.conf|awk -F'\=' {'print $2'}`))", &stdout, &stderr);
```

**Comment by Yannik** [comment]
That works fine.

**Comment by jp112sdl** [comment]
So I can put this in this script.

Thanks!
